### ISSUE TITLE
New Form Field: Checkbox with ranking

### ISSUE THREAD

**Issue by samvthom16** [Sputznik/space-survey#33]
https://dyzz9obi78pm5.cloudfront.net/app/image/id/57a367c291121c3b6ddc9666/n/draganddropmobile.gif

@psychome004 we need to make something like this

**Comment by samvthom16** [comment]
@psychome004 did you test this out on the small screens? Client is complaining that the rank elements are falling in the next line. Can you check this out and push a hotfix?

**Comment by samvthom16** [comment]
Include these styles:
`.space-choice.rank-field{ width: 100%; max-width: 450px; }`
`.space-choice.rank-field > .choice-type { max-width: calc( 100% - 90px ); width: 100%; }`

**Comment by psychome004** [comment]
> `.`

@samvthom16  Done..

**Comment by psychome004** [comment]
> Include these styles:
> `.space-choice.rank-field{ width: 100%; max-width: 450px; }`
> `.space-choice.rank-field > .choice-type { max-width: calc( 100% - 90px ); width: 100%; }`

@samvthom16 Done.
